source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!
use_frameworks!

def import_pods
    pod 'WKZombie', :path => '../'
end

target 'Example iOS' do
	platform :ios, '9.1'
	import_pods
end

target 'Example OSX' do
	platform :osx, '10.11'
	import_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
      end
  end
end
