source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!
use_frameworks!

def import_pods
    pod 'WKZombie', :path => '../'
end

target 'Example iOS' do
	platform :ios, '9.1'
	import_pods
end

target 'Example OSX' do
	platform :osx, '10.11'
	import_pods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'WKZombie-iOS'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DWKZOMBIE_LOGGING_ON'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end
